version: 2.1

# ---------------------------------------------------------------------------- #

workflows:

  version: 2

  tag:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - versions:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - package-docker:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/

  commit:
    jobs:
      - checkout
      - versions
      - package-docker

# ---------------------------------------------------------------------------- #

executors:

  git:
    docker:
      - image: docker.io/alpine/git

  go:
    docker:
      - image: docker.io/jancajthaml/go:latest

  debian:
    docker:
      - image: docker.io/jancajthaml/debian-packager:latest

  machine:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: false

# ---------------------------------------------------------------------------- #

jobs:

  # -------------------------------------------------------------------------- #

  checkout:
    executor: git
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - save_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /mnt/ramdisk/.git
            - /mnt/ramdisk/Dockerfile

  # -------------------------------------------------------------------------- #

  versions:
    executor: git
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - run:
          name: Update FULL_VERSION + SHORT_VERSION
          command: |
            if [ -z ${CIRCLE_TAG} ] ; then
              tags=$(git tag --sort=-v:refname | head -1)
              if [ -z ${tags} ] ; then
                VERSION=v0.0.0
              else
                VERSION=${tags}
              fi
              META=$(echo -e ${CIRCLE_BRANCH} | sed 's:.*/::')
              echo -e "${VERSION#v}" > /mnt/ramdisk/SHORT_VERSION
              echo -e "${VERSION}-${META}" > /mnt/ramdisk/FULL_VERSION
            else
              echo -e "${CIRCLE_TAG#v}" > /mnt/ramdisk/SHORT_VERSION
              echo -e "${CIRCLE_TAG}-master" > /mnt/ramdisk/FULL_VERSION
            fi
      - save_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /mnt/ramdisk/SHORT_VERSION
            - /mnt/ramdisk/FULL_VERSION

  # -------------------------------------------------------------------------- #

  package-docker:
    docker:
      - image: docker.io/docker:18.06.0-ce-git
    working_directory: /mnt/ramdisk
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Package for docker
          command: |
            FULL_VERSION=$(cat /mnt/ramdisk/FULL_VERSION)
            SHORT_VERSION=$(cat /mnt/ramdisk/SHORT_VERSION)

            docker build -t docker.io/openbank/postgres:${FULL_VERSION} .
            docker build -t docker.pkg.github.com/jancajthaml-openbank/postgres/postgres:${SHORT_VERSION} .
      - run:
          name: Publish to docker.io
          command: |
            echo ${DOCKER_PASSWORD} \
              | docker login -u ${DOCKER_USER} --password-stdin
            VERSION=$(cat /mnt/ramdisk/FULL_VERSION)
            docker push \
              docker.io/openbank/postgres:${VERSION}
            rm -f /root/.docker/config.json
      - run:
          name: Publish to docker.pkg.github.com
          command: |
            echo ${GITHUB_RELEASE_TOKEN} \
              | docker login docker.pkg.github.com -u jancajthaml --password-stdin
            VERSION=$(cat /mnt/ramdisk/SHORT_VERSION)
            docker push \
              docker.pkg.github.com/jancajthaml-openbank/postgres/postgres:${VERSION}
            rm -f /root/.docker/config.json

# ---------------------------------------------------------------------------- #
