version: 2.1

# ---------------------------------------------------------------------------- #

workflows:

  version: 2

  tag:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - package-debian:
          matrix:
            parameters:
              arch: [amd64, arm64]
          requires:
            - checkout
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - package-docker:
          matrix:
            parameters:
              arch: [amd64, arm64]
          requires:
            - package-debian-<< matrix.arch >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - publish:
          requires:
            - package-docker
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/

  commit:
    jobs:
      - checkout
      - package-debian:
          matrix:
            parameters:
              arch: [amd64, arm64]
          requires:
            - checkout
      - package-docker:
          matrix:
            parameters:
              arch: [amd64, arm64]
          requires:
            - package-debian-<< matrix.arch >>
      - publish:
          requires:
            - package-docker

# ---------------------------------------------------------------------------- #

executors:

  git:
    docker:
      - image: docker.io/alpine/git
    resource_class: small

  docker:
    docker:
      - image: docker.io/amd64/docker
    resource_class: small

  debian:
    docker:
      - image: docker.io/jancajthaml/debian-packager
    resource_class: small

  machine-arm64:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: false
    resource_class: arm.medium

  machine-amd64:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: false
    resource_class: medium

# ---------------------------------------------------------------------------- #

jobs:

  # -------------------------------------------------------------------------- #

  checkout:
    executor: git
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Update VERSION + META
          command: |
            if [ -z "<< pipeline.git.tag >>" ] ; then
              tags=$(git tag --sort=-v:refname | head -1)
              if [ -z ${tags} ] ; then
                echo -e "0.0.0" > /home/circleci/project/VERSION
              else
                echo -e "${tags#v}" > /home/circleci/project/VERSION
              fi
              echo -e "<< pipeline.git.branch >>" | sed 's:.*/::' > /home/circleci/project/META
            else
              echo -e "<< pipeline.git.tag >>" | sed -e "s/^v//" > /home/circleci/project/VERSION
              echo -e "main" > /home/circleci/project/META
            fi
      - save_cache:
          key: code-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
          paths:
            - /home/circleci/project/.git
            - /home/circleci/project/dev
            - /home/circleci/project/packaging
      - save_cache:
          key: versions-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
          paths:
            - /home/circleci/project/VERSION
            - /home/circleci/project/META

  # -------------------------------------------------------------------------- #

  package-debian:
    executor: debian
    parameters:
      arch:
        type: string
    working_directory: /home/circleci/project
    steps:
      - restore_cache:
          key: code-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
      - restore_cache:
          key: versions-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
      - run:
          name: Package for debian
          command: |
            VERSION=$(cat /home/circleci/project/VERSION)
            /home/circleci/project/dev/lifecycle/debian \
              --arch << parameters.arch >> \
              --pkg postgres \
              --version ${VERSION} \
              --source /home/circleci/project/packaging
          no_output_timeout: 5m
      - save_cache:
          key: debian-<< parameters.arch >>-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
          paths:
            - /home/circleci/project/packaging/bin

  # -------------------------------------------------------------------------- #

  package-docker:
    parameters:
      arch:
        type: string
    executor: machine-<< parameters.arch >>
    working_directory: /home/circleci/project
    steps:
      - restore_cache:
          key: code-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
      - restore_cache:
          key: debian-<< parameters.arch >>-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
      - restore_cache:
          key: versions-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
      - run:
          name: Package for docker << parameters.arch >>
          command: |
            mkdir -p tmp

            docker build \
              -t postgres:<< parameters.arch >>-<< pipeline.git.revision >> \
              -f ./packaging/docker/<< parameters.arch >>/Dockerfile .

            docker save \
              postgres:<< parameters.arch >>-<< pipeline.git.revision >> \
              > tmp/docker-postgres-<< parameters.arch >>-<< pipeline.git.revision >>.tar
      - save_cache:
          key: docker-<< parameters.arch >>-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
          paths:
            - /home/circleci/project/tmp

  # -------------------------------------------------------------------------- #

  publish:
    executor: docker
    working_directory: /home/circleci/project
    steps:
      - restore_cache:
          key: versions-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
      - restore_cache:
          key: docker-arm64-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
      - restore_cache:
          key: docker-amd64-<< pipeline.git.tag >>-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-<< pipeline.git.revision >>
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Restore docker image
          command: |
            docker load < tmp/docker-postgres-arm64-<< pipeline.git.revision >>.tar
            docker load < tmp/docker-postgres-amd64-<< pipeline.git.revision >>.tar
      - run:
          name: Publish to docker.io
          command: |
            export VERSION=$(cat /home/circleci/project/VERSION)
            export META=$(cat /home/circleci/project/META)

            docker tag postgres:amd64-<< pipeline.git.revision >> docker.io/openbank/postgres:amd64-${VERSION}.${META}
            docker tag postgres:arm64-<< pipeline.git.revision >> docker.io/openbank/postgres:arm64-${VERSION}.${META}

            echo ${DOCKER_PASSWORD} | docker login docker.io -u ${DOCKER_USER} --password-stdin

            docker push docker.io/openbank/postgres:amd64-${VERSION}.${META}
            docker push docker.io/openbank/postgres:arm64-${VERSION}.${META}

            rm -f /home/circleci/.docker/config.json
      - run:
          name: Publish to docker.pkg.github.com
          command: |
            export VERSION=$(cat /home/circleci/project/VERSION)

            docker tag postgres:amd64-<< pipeline.git.revision >> docker.pkg.github.com/jancajthaml-openbank/postgres/postgres:amd64-${VERSION}
            docker tag postgres:arm64-<< pipeline.git.revision >> docker.pkg.github.com/jancajthaml-openbank/postgres/postgres:arm64-${VERSION}

            echo ${GITHUB_RELEASE_TOKEN} | docker login docker.pkg.github.com -u ${DOCKER_USER} --password-stdin

            docker push docker.pkg.github.com/jancajthaml-openbank/postgres/postgres:amd64-${VERSION}
            docker push docker.pkg.github.com/jancajthaml-openbank/postgres/postgres:arm64-${VERSION}

            rm -f /home/circleci/.docker/config.json

# ---------------------------------------------------------------------------- #
