version: 2.1

# ---------------------------------------------------------------------------- #

workflows:

  version: 2

  tag:
    jobs:
      - checkout:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - versions:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
      - package-docker:
          matrix:
            parameters:
              arch: [amd64, arm64]
          requires:
            - checkout
            - versions
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/

  commit:
    jobs:
      - checkout
      - versions
      - package-docker:
          matrix:
            parameters:
              arch: [amd64, arm64]
          requires:
            - checkout
            - versions

# ---------------------------------------------------------------------------- #

executors:

  git:
    docker:
      - image: docker.io/alpine/git

  arm64-testbed:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: false
      resource_class: arm.medium

  amd64-testbed:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: false
      resource_class: medium

# ---------------------------------------------------------------------------- #

jobs:

  # -------------------------------------------------------------------------- #

  checkout:
    executor: git
    working_directory: /home/circleci/project
    steps:
      - checkout
      - save_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /home/circleci/project/.git
            - /home/circleci/project/packaging/docker
            - /home/circleci/project/init.sql

  # -------------------------------------------------------------------------- #

  versions:
    executor: git
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Update VERSION + META
          command: |
            if [ -z ${CIRCLE_TAG} ] ; then
              tags=$(git tag --sort=-v:refname | head -1)
              if [ -z ${tags} ] ; then
                VERSION=v0.0.0
              else
                VERSION=${tags}
              fi
              META=$(echo -e ${CIRCLE_BRANCH} | sed 's:.*/::')
              echo -e "${VERSION#v}" > /home/circleci/project/VERSION
              echo -e "${META}" > /home/circleci/project/META
            else
              echo -e "${CIRCLE_TAG#v}" > /home/circleci/project/VERSION
              echo -e "main" > /home/circleci/project/META
            fi
      - save_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - /home/circleci/project/META
            - /home/circleci/project/VERSION

  # -------------------------------------------------------------------------- #

  package-docker:
    parameters:
      arch:
        type: string
    executor: << parameters.arch >>-testbed
    working_directory: /home/circleci/project
    steps:
      - restore_cache:
          key: code-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: versions-{{ .Environment.CIRCLE_TAG }}-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Package for docker << parameters.arch >>
          command: |
            export VERSION=$(cat /home/circleci/project/VERSION)
            export META=$(cat /home/circleci/project/META)
            export ARCH=<< parameters.arch >>

            docker build \
              -t docker.io/openbank/postgres:${ARCH}-${VERSION}.${META} \
              -f ./packaging/docker/${ARCH}/Dockerfile .
            
            docker build \
              -t docker.pkg.github.com/jancajthaml-openbank/postgres/postgres:${ARCH}-${VERSION} \
              -f ./packaging/docker/${ARCH}/Dockerfile .
      - run:
          name: Publish to docker.io
          command: |
            export VERSION=$(cat /home/circleci/project/VERSION)
            export META=$(cat /home/circleci/project/META)
            export ARCH=<< parameters.arch >>

            echo ${DOCKER_PASSWORD} | docker login docker.io -u ${DOCKER_USER} --password-stdin

            docker push \
              docker.io/openbank/postgres:${ARCH}-${VERSION}.${META}

            rm -f /home/circleci/.docker/config.json
      - run:
          name: Publish to docker.pkg.github.com
          command: |
            export VERSION=$(cat /home/circleci/project/VERSION)
            export ARCH=<< parameters.arch >>

            echo ${GITHUB_RELEASE_TOKEN} | docker login docker.pkg.github.com -u ${DOCKER_USER} --password-stdin

            docker push \
              docker.pkg.github.com/jancajthaml-openbank/postgres/postgres:${ARCH}-${VERSION}

            rm -f /home/circleci/.docker/config.json

# ---------------------------------------------------------------------------- #
